app/backend_requests/chat/models/chat.py
from ..models import db
from bson.objectid import ObjectId
from typing import Optional
from .user import User


class Chat():
    table = db.chat

    chat_id: Optional['str'] = None
    user: Optional['User'] = None

    @property
    def _insert_doc(self):
        doc = self.full_doc
        doc.pop('_id')
        doc["user_id"] = ObjectId(doc["user_id"])
        return doc

    @property
    def full_doc(self) -> dict:
        return {"_id": str(self.chat_id), "user_id": str(self.user.user_id)}

    def _insert(self) -> str:
        inserted_id = self.table.insert_one(self._insert_doc).inserted_id
        self.chat_id = inserted_id
        return inserted_id

    @classmethod
    def get_by_user_id(cls, user_id: str) -> Optional['Chat']:
        chat_dict = cls.table.find_one({"user_id": ObjectId(user_id)})
        if chat_dict:
            return cls.from_dict(chat_dict)
        else:
            return None

    @classmethod
    def get_by_id(cls, chat_id: str) -> Optional['Chat']:
        chat_dict = cls.table.find_one({"_id": ObjectId(chat_id)})
        if chat_dict:
            return cls.from_dict(chat_dict)
        else:
            return None

    @classmethod
    def from_dict(cls, chat_dict: dict) -> 'Chat':
        chat = Chat()
        chat.chat_id = ObjectId(chat_dict["_id"])
        chat.user = User.get_by_id(chat_dict["user_id"])
        return chat

    @classmethod
    def from_user_id(cls, user_id: str) -> 'Chat':
        chat = cls.get_by_user_id(user_id)
        if not chat:
            chat = Chat()
            chat.user = User.get_by_id(user_id)
            chat._insert()
        return chat

app/backend_requests/chat/controllers/chat.py
from app.backend_requests.backend_requests import BackendRequest
from flask import redirect, url_for, render_template


class Chat(BackendRequest):
    def __init__(self, req_content: dict):
        super().__init__(req_content)

    def process(self):
        if not self.isLogged():
            return redirect(url_for('.login'))

        return render_template('./chat.html')

app/backend_requests/chat/controllers/login.py
from flask import redirect, url_for, render_template, flash
from app.backend_requests.chat.models.user import User
from app.backend_requests.backend_requests import BackendRequest


class ChatLogin(BackendRequest):
    def __init__(self, req_content: dict):
        super().__init__(req_content)
        self.username = self._parse_param(req_content, 'user', str, optional=True)

    def process(self):
        if self.isLogged():
            return redirect(url_for('.index'))

        if self.username:
            user = User.from_name(self.username)
            self.login_user(user.full_doc)
            return redirect(url_for('.index'))

        return render_template('./login.html', title='Чат')

app/backend_requests/chat/routes.py
from flask import Blueprint, request
from app.backend_requests.backend_requests import BackendRequest
from .controllers.chat import Chat
from .controllers.login import ChatLogin
from .controllers.logout import ChatLogout

chat = Blueprint('chat', __name__, template_folder='templates', static_folder='static')


@chat.route('/')
def index():
    return BackendRequest.call(Chat, request)


@chat.route('/login', methods=["GET", "POST"])
def login():
    return BackendRequest.call(ChatLogin, request)


@chat.route('/logout', methods=["GET", "POST"])
def logout():
    return BackendRequest.call(ChatLogout, request)

app/backend_requests/chat/templates/base_chat.html
<!DOCTYPE html>
<html>
<head>
<link type="text/css" href="{{ url_for('static', filename='css/styles.css')}}" rel="stylesheet" />
<title>{{ title }}</title>
</head>
<body>
{% if menu -%}
	<ul class="mainmenu">
	{% for p in menu %}
	<li><a href="{{ url_for(p.url) }}">{{p.title}}</a></li>
	{% endfor %}
	</ul>
	<div class="clear"></div>
{%- endif -%}
<div class="content">
{% block content -%}
{% endblock %}
</div>
</body>
</html>

app/backend_requests/chat/templates/chat.html
<html>
<head>
    <title>Romashka chat:</title>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="//cdn.socket.io/4.4.1/socket.io.min.js"></script>
    <script type="text/javascript" charset="utf-8">
        var socket;
        $(document).ready(function () {
            socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
            socket.on('connect', function () {
                socket.emit('joined', {});
            });
            socket.on('status', function (data) {
                $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                $('#chat').scrollTop($('#chat')[0].scrollHeight);
            });
            socket.on('message', function (data) {
                $('#chat').val($('#chat').val() + data.msg + '\n');
                $('#chat').scrollTop($('#chat')[0].scrollHeight);
            });
            $('#text').keypress(function (e) {
                var code = e.keyCode || e.which;
                if (code == 13) {
                    text = $('#text').val();
                    $('#text').val('');
                    socket.emit('text', {msg: text});
                }
            });
        });

        function leave_room() {
            socket.emit('left', {}, function () {
                socket.disconnect();

                // go back to the login page
                window.location.href = "{{ url_for('chat.logout') }}";
            });
        }
    </script>
</head>
<body>
<h1>Romashka chat:</h1>
<textarea id="chat" cols="80" rows="20"></textarea><br><br>
<input id="text" size="80" placeholder="Enter your message here"><br><br>
<a href="#" onclick="leave_room();">Leave this room</a>
</body>
</html>

app/backend_requests/chat/templates/index.html
{% extends './base_chat.html' %}

{% block content %}
{{ super() }}
{% endblock %}

app/backend_requests/chat/templates/login.html
{% extends './base_chat.html' %}

{% block content %}
{{ super() }}
<div id="login" class="wnd_dlg_back login_wnd">
<div class="login">
	<p class="title">Чат</p>
{% for cat, msg in get_flashed_messages(True) %}
<div class="flash {{cat}}">{{msg}}</div>
{% endfor %}
	<form action="" method="post">
		<p><label class="form-label">Имя пользователя: </label><input type="text" name="user" />
		<p><input class="login_button" type="submit" value="Войти">
	</form>
</div>
</div>{% endblock %}